name: zuri_call
description: Flutter mobile MVP for the Zuri VoIP calling app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  flutter:
    sdk: flutter
  flutter_contacts: ^2.2.0
  http: ^1.6.0
  shared_preferences: ^2.5.5
  tabler_icons: ^2.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
